import { chromium, expect } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome'});const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.url().includes('cloudfunctions.net'))requests.push({url:r.url(),status:r.status()});});
const email=`muanoluxe-qa-${Date.now()}@example.invalid`;
const result={email,checks:[],errors,requests};
try{
 await page.goto('https://muanoluxe.web.app/',{waitUntil:'domcontentloaded'});await expect(page.locator('.product-card')).toHaveCount(4,{timeout:30000});result.checks.push('Live catalog loads four approved preview pieces');
 await page.getByRole('button',{name:'View The Signature Blazer',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'M',exact:true}).click();await page.getByRole('button',{name:'Add to bag',exact:true}).click();await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'Shopping bag, 1 items'}).click();await expect(page.getByRole('button',{name:'Checkout opening soon'})).toBeDisabled();await page.getByRole('button',{name:'Close dialog'}).click();result.checks.push('Live checkout is visibly disabled');
 await page.getByRole('button',{name:'Open shopping assistant'}).click();await page.getByRole('textbox',{name:'Message the assistant'}).fill('What colours does the Signature Blazer come in?');await page.getByRole('button',{name:'Send message',exact:true}).click();await expect(page.locator('.chat-messages .assistant')).toHaveCount(2,{timeout:45000});result.assistant=await page.locator('.chat-messages .assistant').last().innerText();await expect(page.locator('.chat-messages .assistant').last()).toContainText(/Ivory|Onyx|Sand/i);result.checks.push('Live Gemini responds using actual catalog colours');await page.getByRole('button',{name:'Close assistant'}).click();
 await page.getByRole('textbox',{name:'Newsletter email address'}).fill(email);await page.locator('.newsletter-consent input').check();await page.getByRole('button',{name:'Subscribe to newsletter'}).click();await expect(page.getByRole('status')).toContainText('on the list',{timeout:30000});result.checks.push('Live subscription succeeds through App Check and server validation');
 await page.goto('https://muanoluxe.web.app/admin');await expect(page.getByRole('button',{name:'Continue with Google'})).toBeVisible({timeout:15000});await expect(page.getByRole('button',{name:'Products',exact:true})).toHaveCount(0);result.checks.push('Unauthenticated users cannot access the management studio');
 await page.screenshot({path:'artifacts/live-admin-login.png',fullPage:true});
 const denied=await page.request.post('https://europe-west1-muanoluxe.cloudfunctions.net/subscribe',{data:{data:{email:'unauthorized@example.invalid',consent:true}}});result.appCheckWithoutToken=denied.status();
}catch(e){result.failure=e.message;process.exitCode=1;}finally{await writeFile('artifacts/live-verification.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();}
